[[variable]]
name = "air_temperature"
description = "Air temperature profile"
unit = "C"
initialised_by = ["abiotic", "abiotic_simple"]
updated_by = ["abiotic", "abiotic_simple"]
used_by = [ "abiotic", "abiotic_simple", "plants", "animals"]

[[variable]]
name = "air_temperature_ref"
description = "Air temperature at reference height (2m)"
unit = "C"
initialised_by = "external"
updated_by = ""
used_by = ["abiotic", "abiotic_simple"]

[[variable]]
name = "albedo_shortwave"
description = "Shortwave light albedo"
unit = "-"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic"]

[[variable]]
name = "albedo_vis"
description = "Visible light albedo"
unit = "-"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic"]

[[variable]]
name = "animal_respiration"
description = "Animal respiration aggregated over all functional types"
unit = "ppm"
initialised_by = "animals"
updated_by = "animals"
used_by = [ "abiotic", "animals"]

[[variable]]
name = "atmospheric_co2"
description = "Atmospheric CO2 concentration profile"
unit = "ppm"
initialised_by = ["abiotic", "abiotic_simple"]
updated_by = ["abiotic", "abiotic_simple"]
used_by = ["abiotic", "abiotic_simple", "plants"]

[[variable]]
name = "atmospheric_co2_ref"
description = "Atmospheric CO2 concentration at reference height (above canopy)"
unit = "ppm"
initialised_by = "external"
updated_by = ""
used_by = ["abiotic", "abiotic_simple"]

[[variable]]
name = "atmospheric_pressure"
description = "Atmospheric pressure profile"
unit = "kPa"
initialised_by = ["abiotic", "abiotic_simple"]
updated_by = ["abiotic", "abiotic_simple"]
used_by = ["abiotic", "abiotic_simple", "hydrology", "plants"]

[[variable]]
name = "atmospheric_pressure_ref"
description = "Atmospheric pressure at reference height (2m)"
unit = "kPa"
initialised_by = "external"
updated_by = ""
used_by = ["abiotic", "abiotic_simple", "hydrology"]

[[variable]]
name = "bulk_aerodynamic_resistance"
description = "Bulk aerodynamic resistance"
unit = "s m-1"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "canopy_absorption"
description = "Shortwave radiation absorbed by individual canopy layers"
unit = "J m-2"
initialised_by = "plants"
updated_by = "plants"
used_by = [ "abiotic", "plants"]

[[variable]]
name = "canopy_height"
description = "Canopy height"
unit = "m"
initialised_by = "plants"
updated_by = "plants"
used_by = ["abiotic", "abiotic_simple", "plants"]

[[variable]]
name = "layer_heights"
description = "Heights of canopy layers"
unit = "m"
initialised_by = "plants"
updated_by = "plants"
used_by = ["abiotic", "abiotic_simple", "plants"]

[[variable]]
name = "canopy_temperature"
description = "Canopy temperature of individual layers"
unit = "C"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "elevation"
description = "Elevation above sea level"
unit = "m"
initialised_by = "external"
updated_by = ""
used_by = [ "hydrology"]

[[variable]]
name = "evapotranspiration"
description = "Evapotranspiration"
initialised_by = "plants"
updated_by = "plants"
used_by = ["abiotic", "abiotic_simple", "hydrology", "plants"]

[[variable]]
name = "friction_velocity"
description = "Friction velocity"
unit = "m s-1"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic"]

[[variable]]
name = "ground_heat_flux"
description = "Ground heat flux"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "latent_heat_flux_canopy"
description = "Latent heat flux from canopy layers"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "latent_heat_flux_soil"
description = "Latent heat flux from surface layer"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "leaf_area_index"
description = "Leaf area index"
unit = "m m"
initialised_by = "plants"
updated_by = "plants"
used_by = ["abiotic", "abiotic_simple", "hydrology", "plants"]

[[variable]]
name = "longwave_canopy"
description = "Longwave radiation from individual canopy layers"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "longwave_soil"
description = "Longwave radiation from surface layer"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "mean_annual_temperature"
description = "Mean annual temperature = temperature of deepest soil layer"
unit = "C"
initialised_by = "external"
updated_by = ""
used_by = ["abiotic", "abiotic_simple"]

[[variable]]
name = "molar_density_air"
description = "Temperature-dependent molar density of air"
unit = "kg m-3"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "netradiation_surface"
description = "Net shortwave radiation at the surface"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "plant_net_co2_assimilation"
description = "Plant net CO2 assimilation"
unit = "ppm"
initialised_by = "plants"
updated_by = "plants"
used_by = [ "abiotic", "plants"]

[[variable]]
name = "ppfd"
description = "Top of canopy photosynthetic photon flux density"
unit = "mol m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic", "plants"]

[[variable]]
name = "precipitation"
description = "Precipitation"
unit = "mm"
initialised_by = "external"
updated_by = ""
used_by = [ "hydrology"]

[[variable]]
name = "precipitation_surface"
description = "Precipitation that reaches surface"
unit = "mm"
initialised_by = "hydrology"
updated_by = ""
used_by = [ "hydrology", "plants]

[[variable]]
name = "relative_humidity"
description = "Relative humidity profile"
unit = "%"
initialised_by = ["abiotic", "abiotic_simple"]
updated_by = ["abiotic", "abiotic_simple"]
used_by = ["abiotic", "abiotic_simple", "hydrology", "plants"]

[[variable]]
name = "relative_humidity_ref"
description = "Relative humidity at reference height (2m)"
unit = "%"
initialised_by = "external"
updated_by = ""
used_by = ["abiotic", "abiotic_simple", "hydrology"]

[[variable]]
name = "river_discharge"
description = "River discharge"
unit = "m3 s-1"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology"]

[[variable]]
name = "stream_flow"
description = "Estimated stream flow"
unit = "mm per time step"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology"]

[[variable]]
name = "roughness_length_momentum"
description = "Roughness length for momentum"
unit = "m"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "sensible_heat_flux"
description = "Sensible heat flux from canopy and surface"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "sensible_heat_flux_canopy"
description = "Sensible heat flux from canopy"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "sensible_heat_flux_soil"
description = "Sensible heat flux from surface layer"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "shortwave_in"
description = "Downward shortwave radiation"
unit = "J m-2"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic"]

[[variable]]
name = "soil_evaporation"
description = "Soil evaporation"
unit = "mm"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = ["abiotic", "hydrology"]

[[variable]]
name = "soil_moisture"
description = "Soil moisture as volumetric relative water content"
unit = "-"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = ["abiotic", "abiotic_simple", "hydrology", "soil"]

[[variable]]
name = "soil_respiration"
description = "Soil respiration"
unit = "ppm"
initialised_by = "soil"
updated_by = "soil"
used_by = [ "abiotic", "soil"]

[[variable]]
name = "soil_temperature"
description = "Soil temperature profile"
unit = "C"
initialised_by = ["abiotic", "abiotic_simple]
updated_by = ["abiotic", "abiotic_simple"]
used_by = ["abiotic", "abiotic_simple", "soil"]

[[variable]]
name = "specific_heat_air"
description = "Specific heat of air"
unit = "kJ kg-1"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = ["abiotic"]

[[variable]]
name = "specific_humidity"
description = "Specific humidity of air"
unit = "g kg-1"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic", "plants"]

[[variable]]
name = "subsurface_runoff"
description = "Subsurface runoff"
unit = "mm"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology", "soil"]

[[variable]]
name = "sunshine_fraction"
description = "Fraction of sunshine hours, between 0 and 1"
unit = "-"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic"]

[[variable]]
name = "surface_runoff"
description = "Surface runoff generated in each grid cell"
unit = "mm"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology", "soil"]

[[variable]]
name = "surface_runoff_accumulated"
description = "Accumlated surface runoff"
unit = "mm"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology"]

[[variable]]
name = "surface_water"
description = "Searchable surface water"
unit = "%"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology", "soil", "animal"]

[[variable]]
name = "topofcanopy_radiation"
description = "Top of canopy downward shortwave radiation"
unit = "J m-2"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "vertical_flow"
description = "Vertical flow of water through soil column"
unit = "mm per time step"
initialised_by = "hydrology"
updated_by = "hydrology"
used_by = [ "hydrology", "soil"]

[[variable]]
name = "wind_above_canopy"
description = "Wind above canopy"
unit = "m s-1"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic"]

[[variable]]
name = "wind_below_canopy"
description = "Wind profile within and below canopy"
unit = "m s-1"
initialised_by = "abiotic"
updated_by = "abiotic"
used_by = [ "abiotic", "hydrology"]

[[variable]]
name = "wind_speed_ref"
description = "Wind speed at reference height (10m)"
unit = "m s-1"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic", "hydrology"]

[[variable]]
name = "soil_c_pool_lmwc"
description = "Size of low molecular weight carbon pool"
unit = "kg C m-3"
initialised_by = "soil"
updated_by = "soil"
used_by = [ "plants", "soil"]

[[variable]]
name = "soil_c_pool_maom"
description = "Size of mineral associated organic matter pool"
unit = "kg C m-3"
initialised_by = "soil"
updated_by = "soil"
used_by = [ "soil"]

[[variable]]
name = "soil_c_pool_microbe"
description = "Size of microbial biomass pool"
unit = "kg C m-3"
initialised_by = "soil"
updated_by = "soil"
used_by = [ "soil"]

[[variable]]
name = "soil_c_pool_pom"
description = "Size of microbial biomass pool"
unit = "kg C m-3"
initialised_by = "soil"
updated_by = "soil"
used_by = ["soil"]

[[variable]]
name = "bulk_density"
description = "Bulk density of soil"
unit = "kg m-3"
initialised_by = "external"
updated_by = "soil"
used_by = [ "abiotic", "soil"]

[[variable]]
name = "percent_clay"
description = "Clay as a percentage of total soil"
unit = "%"
initialised_by = "external"
updated_by = ""
used_by = [ "abiotic", "soil"]

[[variable]]
name = "pH"
description = "Soil pH"
unit = "pH"
initialised_by = "external"
updated_by = "soil"
used_by = [ "soil"]

[[variable]]
name = "litter_pool_above_metabolic"
description = "Above ground metabolic litter pool"
unit = "kg C m^-2"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "litter"]

[[variable]]
name = "litter_pool_above_structural"
description = "Above ground structural litter pool"
unit = "kg C m^-2"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "litter"]

[[variable]]
name = "litter_pool_woody"
description = "Woody litter pool"
unit = "kg C m^-2"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "litter"]

[[variable]]
name = "litter_pool_below_metabolic"
description = "Below ground metabolic litter pool"
unit = "kg C m^-2"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "litter"]

[[variable]]
name = "litter_pool_below_structural"
description = "Below ground structural litter pool"
unit = "kg C m^-2"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "litter"]

[[variable]]
name = "litter_C_mineralisation_rate"
description = "Rate of carbon addition to soil from litter"
unit = "kg C m^-3 day^-1"
initialised_by = "litter"
updated_by = "litter"
used_by = [ "soil"]

[[variable]]
name = "decomposed_excrement"
description = "Rate of excrement flow from animals into litter"
unit = "kg C m^-3 day^-1"
initialised_by = "animals"
updated_by = "animals"
used_by = [ "litter"]

[[variable]]
name = "decomposed_carcasses"
description = "Rate of decomposed carcass biomass flow from animals into litter"
unit = "kg C m^-3 day^-1"
initialised_by = "animals"
updated_by = "animals"
used_by = [ "litter"]