# animal_functional_groups.toml

[[animal.functional_groups]]
name = "carnivorous_bird"
taxa = "bird"
diet = "carnivore"
metabolic_type = "endothermic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_bird"
excretion_type = "uricotelic"
birth_mass = 0.1
adult_mass = 1.0

[[animal.functional_groups]]
name = "herbivorous_bird"
taxa = "bird"
diet = "herbivore"
metabolic_type = "endothermic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_bird"
excretion_type = "uricotelic"
birth_mass = 0.05
adult_mass = 0.5

[[animal.functional_groups]]
name = "carnivorous_mammal"
taxa = "mammal"
diet = "carnivore"
metabolic_type = "endothermic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_mammal"
excretion_type = "ureotelic"
birth_mass = 4.0
adult_mass = 40.0

[[animal.functional_groups]]
name = "herbivorous_mammal"
taxa = "mammal"
diet = "herbivore"
metabolic_type = "endothermic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_mammal"
excretion_type = "ureotelic"
birth_mass = 1.0
adult_mass = 10.0

[[animal.functional_groups]]
name = "carnivorous_insect"
taxa = "insect"
diet = "carnivore"
metabolic_type = "ectothermic"
reproductive_type = "iteroparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "carnivorous_insect"
excretion_type = "uricotelic"
birth_mass = 0.001
adult_mass = 0.01

[[animal.functional_groups]]
name = "herbivorous_insect"
taxa = "insect"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_type = "semelparous"
development_type = "direct"
development_status = "adult"
offspring_functional_group = "herbivorous_insect"
excretion_type = "uricotelic"
birth_mass = 0.0005
adult_mass = 0.005

[[animal.functional_groups]]
name = "butterfly"
taxa = "insect"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_type = "semelparous"
development_type = "indirect"
development_status = "adult"
offspring_functional_group = "caterpillar"
excretion_type = "uricotelic"
birth_mass = 0.0005
adult_mass = 0.005

[[animal.functional_groups]]
name = "caterpillar"
taxa = "insect"
diet = "herbivore"
metabolic_type = "ectothermic"
reproductive_type = "nonreproductive"
development_type = "indirect"
development_status = "larval"
offspring_functional_group = "butterfly"
excretion_type = "uricotelic"
birth_mass = 0.0005
adult_mass = 0.005